### ISSUE TITLE
How to catch Lambda error and jump another State ?

### ISSUE THREAD

**Issue by hangingman** [jhuapl-boss/heaviside#9]
Hi,

I would like to catch Errors on Lambda, then jump to the another previous State.
I tried following DSL:

```
    Pass()
        """check_something"""

    Lambda('xxxx')
        """some_my_func"""
        timeout: 60
        heartbeat: 30
        input: '$'
        output: '$'
        catch []:
            """check_something"""
```

But, it causes error. Is there any suggestion ?

**Comment by derek-pryor** [comment]
Including the error output would be helpful in the future.
___
```
File "issue.hsd", line 11
        """check_something"""
        ^
Syntax Error: Invalid syntax
```

**Comment by derek-pryor** [comment]
Currently Heaviside doesn't support arbitrary state transitions (even though AWS Step Functions do). I've tried to create the most common control flow statements in the Heaviside DSL so that files written in the DSL are easier to follow and to shy away from `goto` style programming.

If your control flow needs are not satisfied by the existing statements something new could be added (either a new control flow structure or just added `goto` support).

**Comment by hangingman** [comment]
@derek-pryor Hi, thank you for your explanation !
I expected the `"""xxx"""` represent the kind of `label` on the general programming language.
And, I'm suffer from lack of function that is state transition. But, it seems heaviside's policy. 
My question would be useful for the people of later.

**Comment by derek-pryor** [comment]
The `"""xxx"""` does label / name the state (instead of the state being called `LineXX`), but cannot be used to create a transition. I am starting to plan for another release of Heaviside and may include a new control flow or `goto` ability.

**Comment by derek-pryor** [comment]
I just created PR #11 that adds this support. I'll be creating the next Heaviside release in a bit after I add some other improvements.

**Comment by derek-pryor** [comment]
@hangingman Heaviside 2.0 was just pushed to PyPi and contains this fix
